<?php

/*
 * This file is part of the Incipio package.
 *
 * (c) Florian Lefevre
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Repository\Publish;

use App\Entity\Publish\Document;
use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    /**
     * @return int
     */
    public function getTotalSize()
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('SUM(d.size)')->from(Document::class, 'd');

        return $query->getQuery()->getSingleScalarResult();
    }
}
