### Espace admin
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /over

Mgate_formation:
    resource: "@MgateFormationBundle/Resources/config/routing.yml"
    prefix:   /

MgateTresoBundle:
    resource: "@MgateTresoBundle/Resources/config/routing.yml"
    prefix:   /Tresorerie

Mgate_stat:
    resource: "@MgateStatBundle/Resources/config/routing.yml"
    prefix:   /

Mgate_dashboard:
    resource: "@MgateDashboardBundle/Resources/config/routing.yml"
    prefix:   /

Mgate_publi:
    resource: "@MgatePubliBundle/Resources/config/routing.yml"
    prefix:   /

Mgate_user:
    resource: "@MgateUserBundle/Resources/config/routing.yml"
    prefix:   /

MgateSuiviBundle:
    resource: "@MgateSuiviBundle/Resources/config/routing.yml"
    prefix:   /suivi

MgatePersonneBundle:
    resource: "@MgatePersonneBundle/Resources/config/routing.yml"
    prefix:   /personne

N7consulting_rh:
    resource: "@N7consultingRhBundle/Resources/config/routing.yml"
    prefix:   /rh

N7consulting_privacy:
    resource: "@N7consultingPrivacyBundle/Controller/"
    type:     annotation
    prefix:   /privacy

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

### FOS User start
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
### FOS User end


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


OuestINSA_Signature:
    resource: "@OuestINSASignatureBundle/Resources/config/routing.yml"
    prefix:   /Signature
