OuestINSA_signature_homepage:
    path:  /
    defaults: { _controller: OuestINSASignatureBundle:Signature:index }

OuestINSA_signature_generate:
    path: generate
    defaults: { _controller: OuestINSASignatureBundle:Signature:generate }